/**
 * The renderer for art that arrives as a stack of transparent PNGs.
 *
 * One of two implementations of `AvatarSet.draw`, and the reason there are two
 * is that a single implementation is indistinguishable from no interface at
 * all. The other is `pixel.ts`, which draws one procedural SVG and shares not
 * a line of this.
 *
 * Compositing is absolutely positioned rectangles in a fixed z order on a
 * fixed canvas. That is all Picrew is, and nothing here should grow past it.
 *
 * Nothing in this file knows what a hair colour looks like or what an outfit
 * is called. It knows that a slot resolves to some number of keys in a table
 * of trimmed images, and it looks them up.
 */

import type { Drawn, DrawnLayer, Loadout, Part, Rect, SetId, Slot } from './types.js';

/** One trimmed PNG and where it sits on the full canvas. `layers.json`. */
export interface Placement extends Rect {
  file: string;
}

export interface LayerTable {
  canvas: { w: number; h: number };
  layers: Record<string, Placement>;
}

/**
 * How one slot's choice becomes keys in the table.
 *
 * A list rather than a single key, because a part may be drawn at more than
 * one depth. Sutemo's hair is the case the whole thing exists for: it comes as
 * a back and a front, and the body and the outfit go between them. Collapsing
 * those into one image loses the only feature that made this set worth
 * extracting.
 */
export interface SlotDraw {
  z: number;
  /**
   * `part` is the id with its slot prefix stripped; `variant` may be empty.
   *
   * The loadout comes too, for the keys that depend on a choice made in a
   * different slot. Skin is the case: a nose is a different sprite per tone
   * and the tone is chosen on the body, so the nose's key has to be able to
   * read it. Sutemo's keys ignore the argument entirely.
   */
  key(part: string, variant: string, loadout: Loadout): string;
  /**
   * The colour to multiply this layer by, or nothing to draw it as drawn.
   *
   * Handed the whole loadout rather than this slot's variant, because the
   * colour of a layer is not always the colour of its slot: a nose is skin,
   * and skin is chosen on the body. See `tint.ts` for what the multiply is.
   */
  tint?(loadout: Loadout): string | undefined;
}

export interface LayeredSpec {
  /** Folder under `sets/`, and the first segment of every `file` emitted. */
  dir: string;
  /**
   * The folder the art is in, under `dir`, and therefore its format.
   *
   * `png` for the two sets drawn as sprites, `webp` for the two that arrived
   * as six thousand painted 128px files, where the format is the difference
   * between a folder and a download. Named here rather than sniffed from the
   * extension, because the consumers resolve a path and one of them
   * (`render-avatars.ts`) has to decode it.
   */
  art?: 'png' | 'webp';
  table: LayerTable;
  /** Drawn whatever is equipped: the body, and anything else always present. */
  base: { z: number; key: string }[];
  draws: Partial<Record<Slot, SlotDraw[]>>;
}

/**
 * Part ids carry their slot: `hair/long`, `outfit/hoodie`.
 *
 * Which means a part is unique across a set without every slot having to
 * invent distinct names, and it means a malformed id is visible in a stack
 * trace. The table keys are built from the tail.
 */
/** Behind everything, and below any z a set is likely to name. */
export const BACKGROUND_Z = -1;

export function partTail(id: string): string {
  const cut = id.indexOf('/');
  return cut < 0 ? id : id.slice(cut + 1);
}

/**
 * Stack one loadout into a list of rectangles.
 *
 * A key the table does not have is skipped rather than thrown. The table is
 * generated by a script from somebody else's PSD, and a half drawn avatar in
 * the customiser is a far better failure than a blank screen in the lobby
 * where the chip lives.
 */
export function drawLayered<S extends SetId>(
  spec: LayeredSpec,
  parts: Part<S>[],
  loadout: Loadout<S>,
): Drawn {
  const stack: { z: number; layer: DrawnLayer }[] = [];

  const push = (z: number, key: string, tint?: string) => {
    const place = spec.table.layers[key];
    if (!place) return;
    stack.push({
      z,
      layer: {
        kind: 'image',
        // The tint is part of the key, not just of the layer. React reuses an
        // `<img>` across renders by key, and a recoloured layer that keeps the
        // old key keeps the old filter until something else invalidates it,
        // which shows up as a hair colour that lags one click behind.
        key: tint ? `${key} ${tint}` : key,
        file: `${spec.dir}/${spec.art ?? 'png'}/${place.file}`,
        x: place.x,
        y: place.y,
        w: place.w,
        h: place.h,
        ...(tint ? { tint } : {}),
      },
    });
  };

  const background = loadout.parts.background;
  if (background && !spec.draws.background) {
    // A set with no background art takes a flat palette token instead, which
    // is resolved here rather than being 30 more PNGs of solid colour that
    // would then be wrong in the other palette. A set that *did* draw its own
    // backgrounds says so with a `background` entry in `draws`, and this is
    // skipped: painting a token under its art would show through the
    // transparent parts of a pattern.
    stack.push({
      z: BACKGROUND_Z,
      layer: { kind: 'fill', key: background, token: `--${partTail(background)}` },
    });
  }

  for (const item of spec.base) push(item.z, item.key);

  for (const [slot, draws] of Object.entries(spec.draws) as [Slot, SlotDraw[]][]) {
    const chosen = loadout.parts[slot];
    if (!chosen) continue;
    const part = parts.find((candidate) => candidate.id === chosen);
    const variant = pickVariant(part, loadout.variants[slot]);
    for (const draw of draws) {
      push(draw.z, draw.key(partTail(chosen), variant, loadout), draw.tint?.(loadout));
    }
  }

  stack.sort((a, b) => a.z - b.z);
  return { canvas: spec.table.canvas, layers: stack.map((item) => item.layer) };
}

/**
 * The variant to draw: the one chosen, or the first the part offers.
 *
 * Falling back rather than drawing nothing, because a stored loadout outlives
 * the art. A set that drops a hair colour would otherwise bald everybody who
 * was wearing it.
 */
export function pickVariant(part: Part | undefined, chosen: string | undefined): string {
  if (!part || part.variants.length === 0) return '';
  if (chosen && part.variants.some((variant) => variant.id === chosen)) return chosen;
  return part.variants[0].id;
}
