// GENERATED by scripts/build-waifu.ts. Do not edit: rerun it.
//
// Metadata only. `image` points at AniList's CDN and no art is stored here;
// see the script's header for why that is deliberate.
import type { Waifu } from './waifu.js';

export const ROSTER: Waifu[] = [
  {
    "id": "anilist:88572",
    "name": "Emilia",
    "series": "Re:ZERO -Starting Life in Another World-",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b88572-IzTwXEHSobRs.jpg",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:40881",
    "name": "Mikasa Ackerman",
    "series": "Attack on Titan",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b40881-F3gr1PkreDvj.png",
    "tags": [
      "action",
      "drama",
      "fantasy",
      "mystery"
    ]
  },
  {
    "id": "anilist:34470",
    "name": "Kurisu Makise",
    "series": "Steins;Gate",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b34470-Jw2LXZBL5R8i.png",
    "tags": [
      "drama",
      "psychological",
      "sci-fi",
      "thriller"
    ]
  },
  {
    "id": "anilist:137080",
    "name": "Makima",
    "series": "Chainsaw Man",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b137080-UHcynYNjb5ZU.png",
    "tags": [
      "action",
      "drama",
      "horror",
      "supernatural"
    ]
  },
  {
    "id": "anilist:127222",
    "name": "Mai Sakurajima",
    "series": "Rascal Does Not Dream of Bunny Girl Senpai",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b127222-Jh5hhP7vZ7s1.png",
    "tags": [
      "comedy",
      "drama",
      "mystery",
      "psychological"
    ]
  },
  {
    "id": "anilist:176754",
    "name": "Frieren",
    "series": "Frieren: Beyond Journey’s End",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b176754-PCnpqIOkjhFk.png",
    "tags": [
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:126824",
    "name": "Maomao",
    "series": "The Apothecary Diaries",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b126824-MqsCncTO1qpv.png",
    "tags": [
      "drama",
      "mystery"
    ]
  },
  {
    "id": "anilist:120649",
    "name": "Kaguya Shinomiya",
    "series": "Kaguya-sama: Love is War",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b120649-NPaWaIpWy60E.png",
    "tags": [
      "comedy",
      "psychological",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:90169",
    "name": "Violet Evergarden",
    "series": "Violet Evergarden",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b90169-4wr1Zehnsac8.png",
    "tags": [
      "drama",
      "fantasy",
      "slice of life"
    ]
  },
  {
    "id": "anilist:137079",
    "name": "Power",
    "series": "Chainsaw Man",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b137079-6yLEUYR3bmpr.png",
    "tags": [
      "action",
      "drama",
      "horror",
      "supernatural"
    ]
  },
  {
    "id": "anilist:500",
    "name": "Sakura Matou",
    "series": "Fate/Zero",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b500-NQrLbnBr1sDv.png",
    "tags": [
      "action",
      "drama",
      "fantasy",
      "supernatural"
    ]
  },
  {
    "id": "anilist:89361",
    "name": "Megumin",
    "series": "KONOSUBA -God's blessing on this wonderful world!",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b89361-tq8PQQ4MmF0M.png",
    "tags": [
      "adventure",
      "comedy",
      "ecchi",
      "fantasy"
    ]
  },
  {
    "id": "anilist:133676",
    "name": "Marin Kitagawa",
    "series": "My Dress-Up Darling",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b133676-kV2czE3C8Qls.png",
    "tags": [
      "comedy",
      "ecchi",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:88575",
    "name": "Rem",
    "series": "Re:ZERO -Starting Life in Another World-",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b88575-Ayu8UPDA8NS6.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:121103",
    "name": "Chika Fujiwara",
    "series": "Kaguya-sama: Love is War",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b121103-UGLxT8utLPnq.png",
    "tags": [
      "comedy",
      "psychological",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:127518",
    "name": "Nezuko Kamado",
    "series": "Demon Slayer: Kimetsu no Yaiba",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b127518-NRlq1CQ1v1ro.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:124382",
    "name": "Ichigo",
    "series": "DARLING in the FRANXX",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b124382-bSBkjtYjJQtr.png",
    "tags": [
      "action",
      "drama",
      "mecha",
      "psychological"
    ]
  },
  {
    "id": "anilist:124381",
    "name": "Zero Two",
    "series": "DARLING in the FRANXX",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b124381-2gAVq76HPfL2.png",
    "tags": [
      "action",
      "drama",
      "mecha",
      "psychological"
    ]
  },
  {
    "id": "anilist:126375",
    "name": "Itsuki Nakano",
    "series": "The Quintessential Quintuplets",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b126375-dEe9IyQ9By09.png",
    "tags": [
      "comedy",
      "drama",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:125886",
    "name": "Miko Iino",
    "series": "Kaguya-sama: Love is War",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b125886-TQbmqAaSgBLS.png",
    "tags": [
      "comedy",
      "psychological",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:22037",
    "name": "Hitagi Senjougahara",
    "series": "Bakemonogatari",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b22037-sY7GWSKYr2Nl.jpg",
    "tags": [
      "comedy",
      "drama",
      "mystery",
      "psychological"
    ]
  },
  {
    "id": "anilist:94",
    "name": "Asuka Langley Souryuu",
    "series": "Neon Genesis Evangelion",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b94-d631a3Z2KPvd.png",
    "tags": [
      "action",
      "drama",
      "mecha",
      "mystery"
    ]
  },
  {
    "id": "anilist:61",
    "name": "Robin Nico",
    "series": "ONE PIECE",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b61-ywXUyyocEEqt.png",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "drama"
    ]
  },
  {
    "id": "anilist:133700",
    "name": "Nobara Kugisaki",
    "series": "JUJUTSU KAISEN",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b133700-f6sOO3TcgLV6.png",
    "tags": [
      "action",
      "drama",
      "supernatural"
    ]
  },
  {
    "id": "anilist:138102",
    "name": "Yor Forger",
    "series": "SPY x FAMILY",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b138102-ZOAu9jI2d5ke.png",
    "tags": [
      "action",
      "comedy",
      "slice of life",
      "supernatural"
    ]
  },
  {
    "id": "anilist:23602",
    "name": "Shinobu Oshino",
    "series": "Bakemonogatari",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b23602-Z4MDNYcoAWZu.png",
    "tags": [
      "comedy",
      "drama",
      "mystery",
      "psychological"
    ]
  },
  {
    "id": "anilist:134167",
    "name": "Maki Zenin",
    "series": "JUJUTSU KAISEN",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b134167-5TCytk45YByD.png",
    "tags": [
      "action",
      "drama",
      "supernatural"
    ]
  },
  {
    "id": "anilist:138100",
    "name": "Anya Forger",
    "series": "SPY x FAMILY",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b138100-4Li0tWRCa5bQ.png",
    "tags": [
      "action",
      "comedy",
      "slice of life",
      "supernatural"
    ]
  },
  {
    "id": "anilist:498",
    "name": "Rin Tohsaka",
    "series": "Fate/Zero",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b498-lwawtSpLyATL.png",
    "tags": [
      "action",
      "drama",
      "fantasy",
      "supernatural"
    ]
  },
  {
    "id": "anilist:497",
    "name": "Artoria Pendragon",
    "series": "Fate/Zero",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b497-Yg5pNmC8kxzs.png",
    "tags": [
      "action",
      "drama",
      "fantasy",
      "supernatural"
    ]
  },
  {
    "id": "anilist:80243",
    "name": "Shouko Nishimiya",
    "series": "A Silent Voice",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b80243-RzxE51iUU5eq.png",
    "tags": [
      "drama",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:66171",
    "name": "Kyouko Hori",
    "series": "Horimiya",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b66171-o2vk3689wWFK.png",
    "tags": [
      "comedy",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:126373",
    "name": "Miku Nakano",
    "series": "The Quintessential Quintuplets",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b126373-CWeyXb822uDN.png",
    "tags": [
      "comedy",
      "drama",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:257562",
    "name": "Hitori Gotou",
    "series": "BOCCHI THE ROCK!",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b257562-Ru35NYPfsqhY.png",
    "tags": [
      "comedy",
      "music",
      "slice of life"
    ]
  },
  {
    "id": "anilist:38005",
    "name": "Homura Akemi",
    "series": "Puella Magi Madoka Magica",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b38005-T3NR8p2f021x.jpg",
    "tags": [
      "action",
      "drama",
      "fantasy",
      "mahou shoujo"
    ]
  },
  {
    "id": "anilist:88350",
    "name": "Roxy Migurdia",
    "series": "Mushoku Tensei: Jobless Reincarnation",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b88350-QU1iwgZ887U8.png",
    "tags": [
      "adventure",
      "drama",
      "ecchi",
      "fantasy"
    ]
  },
  {
    "id": "anilist:86",
    "name": "Rei Ayanami",
    "series": "Neon Genesis Evangelion",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/86-cA1zL7fyls8E.jpg",
    "tags": [
      "action",
      "drama",
      "mecha",
      "mystery"
    ]
  },
  {
    "id": "anilist:188783",
    "name": "Kana Arima",
    "series": "OSHI NO KO",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b188783-77orwP7vNuNg.png",
    "tags": [
      "drama",
      "mystery",
      "psychological",
      "supernatural"
    ]
  },
  {
    "id": "anilist:1259",
    "name": "Misato Katsuragi",
    "series": "Neon Genesis Evangelion",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b1259-afTQkZ5SVMOn.png",
    "tags": [
      "action",
      "drama",
      "mecha",
      "mystery"
    ]
  },
  {
    "id": "anilist:121104",
    "name": "Ai Hayasaka",
    "series": "Kaguya-sama: Love is War",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b121104-7TYRl3EEsDYU.png",
    "tags": [
      "comedy",
      "psychological",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:126372",
    "name": "Nino Nakano",
    "series": "The Quintessential Quintuplets",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b126372-DtorHRgQaYUJ.png",
    "tags": [
      "comedy",
      "drama",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:1111",
    "name": "C.C.",
    "series": "Code Geass: Lelouch of the Rebellion",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b1111-UhmlFtRFrnWa.png",
    "tags": [
      "action",
      "drama",
      "mecha",
      "sci-fi"
    ]
  },
  {
    "id": "anilist:36828",
    "name": "Asuna Yuuki",
    "series": "Sword Art Online",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b36828-j5ib0adAzGMx.png",
    "tags": [
      "action",
      "adventure",
      "fantasy",
      "romance"
    ]
  },
  {
    "id": "anilist:67067",
    "name": "Yukino Yukinoshita",
    "series": "My Teen Romantic Comedy SNAFU",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b67067-gqhgjlni0Bcf.png",
    "tags": [
      "comedy",
      "drama",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:148740",
    "name": "Reze",
    "series": "Chainsaw Man",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b148740-ceAibPxLW8rR.png",
    "tags": [
      "action",
      "drama",
      "horror",
      "supernatural"
    ]
  },
  {
    "id": "anilist:723",
    "name": "Nami",
    "series": "ONE PIECE",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b723-vp5hPptgnNEC.png",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "drama"
    ]
  },
  {
    "id": "anilist:141061",
    "name": "Vladilena Milizé",
    "series": "86 EIGHTY-SIX",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b141061-jqIhB9jmClQ3.png",
    "tags": [
      "action",
      "drama",
      "mecha",
      "sci-fi"
    ]
  },
  {
    "id": "anilist:174873",
    "name": "Kurena Kukumila",
    "series": "86 EIGHTY-SIX",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b174873-FNf08aPYTVXY.jpg",
    "tags": [
      "action",
      "drama",
      "mecha",
      "sci-fi"
    ]
  },
  {
    "id": "anilist:69411",
    "name": "Kaori Miyazono",
    "series": "Your lie in April",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b69411-lxM0FRvWHqlv.png",
    "tags": [
      "drama",
      "music",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:136070",
    "name": "Shinobu Kochou",
    "series": "Demon Slayer: Kimetsu no Yaiba",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b136070-MC9LLxJsHyHE.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:121889",
    "name": "Yumeko Jabami",
    "series": "Kakegurui",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b121889-ABsurpy5SjOW.png",
    "tags": [
      "drama",
      "mystery",
      "psychological"
    ]
  },
  {
    "id": "anilist:154224",
    "name": "Mami Nanami",
    "series": "Rent-a-Girlfriend",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b154224-7dJ09BKEnG3v.png",
    "tags": [
      "comedy",
      "drama",
      "romance"
    ]
  },
  {
    "id": "anilist:125659",
    "name": "Gabi Braun",
    "series": "Attack on Titan Final Season",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b125659-O37MZQWibV7g.png",
    "tags": [
      "action",
      "drama",
      "fantasy",
      "mystery"
    ]
  },
  {
    "id": "anilist:207",
    "name": "Tooru Honda",
    "series": "Fruits Basket (2019)",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b207-RQ4EUdTD0K62.png",
    "tags": [
      "comedy",
      "drama",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:12064",
    "name": "Taiga Aisaka",
    "series": "Toradora!",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b12064-7PDN3ylIeAZn.png",
    "tags": [
      "comedy",
      "drama",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:45887",
    "name": "Sasha Blouse",
    "series": "Attack on Titan",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b45887-QPtJH0KwqthW.jpg",
    "tags": [
      "action",
      "drama",
      "fantasy",
      "mystery"
    ]
  },
  {
    "id": "anilist:81929",
    "name": "Tatsumaki",
    "series": "One-Punch Man",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b81929-WPVp2LQoWgkc.png",
    "tags": [
      "action",
      "comedy",
      "sci-fi",
      "supernatural"
    ]
  },
  {
    "id": "anilist:87277",
    "name": "Touka Kirishima",
    "series": "Tokyo Ghoul",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b87277-oUaqrI1iBzu6.png",
    "tags": [
      "action",
      "drama",
      "horror",
      "mystery"
    ]
  },
  {
    "id": "anilist:284157",
    "name": "Lucy",
    "series": "Cyberpunk: Edgerunners",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b284157-cqYawN7XCNJx.jpg",
    "tags": [
      "action",
      "drama",
      "psychological",
      "sci-fi"
    ]
  },
  {
    "id": "anilist:89362",
    "name": "Aqua",
    "series": "KONOSUBA -God's blessing on this wonderful world!",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b89362-ibkc0eoECaW1.png",
    "tags": [
      "adventure",
      "comedy",
      "ecchi",
      "fantasy"
    ]
  },
  {
    "id": "anilist:83797",
    "name": "Ryuuko Matoi",
    "series": "Kill la Kill",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b83797-ix0Cl5OMfV22.png",
    "tags": [
      "action",
      "comedy",
      "ecchi"
    ]
  },
  {
    "id": "anilist:183965",
    "name": "Fern",
    "series": "Frieren: Beyond Journey’s End",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b183965-uGFohBjlFoTp.png",
    "tags": [
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:458",
    "name": "Revy",
    "series": "Black Lagoon",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b458-tlKqPcuR287U.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "thriller"
    ]
  },
  {
    "id": "anilist:65865",
    "name": "Rikka Takanashi",
    "series": "Love, Chunibyo & Other Delusions",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b65865-AC0ru7cDXUgK.png",
    "tags": [
      "comedy",
      "drama",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:70069",
    "name": "Kurumi Tokisaki",
    "series": "Date A Live",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b70069-DEV7X6o2L7oG.jpg",
    "tags": [
      "action",
      "comedy",
      "ecchi",
      "fantasy"
    ]
  },
  {
    "id": "anilist:702",
    "name": "Nana Oosaki",
    "series": "NANA",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b702-qqO3zbj5hp1l.png",
    "tags": [
      "drama",
      "music",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:121956",
    "name": "Shouko Komi",
    "series": "Komi Can’t Communicate",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b121956-5FbIbcd6gAZW.png",
    "tags": [
      "comedy",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:11222",
    "name": "Jolyne Kuujou",
    "series": "JoJo's Bizarre Adventure: STONE OCEAN",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b11222-Se9QoJHDSeYY.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "supernatural"
    ]
  },
  {
    "id": "anilist:2219",
    "name": "Lain Iwakura",
    "series": "Serial Experiments Lain",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b2219-K3wzEOVwdUhL.png",
    "tags": [
      "drama",
      "mystery",
      "psychological",
      "sci-fi"
    ]
  },
  {
    "id": "anilist:22055",
    "name": "Tsubasa Hanekawa",
    "series": "Bakemonogatari",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b22055-EaTsy30ihdgb.png",
    "tags": [
      "comedy",
      "drama",
      "mystery",
      "psychological"
    ]
  },
  {
    "id": "anilist:63351",
    "name": "Akame",
    "series": "Akame ga Kill!",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b63351-0WmsDENpiscp.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:835",
    "name": "Misa Amane",
    "series": "Death Note",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b835-CiZa8y2z2gCz.png",
    "tags": [
      "mystery",
      "psychological",
      "supernatural",
      "thriller"
    ]
  },
  {
    "id": "anilist:5189",
    "name": "Erza Scarlet",
    "series": "Fairy Tail",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b5189-GR1xdok9SFsN.jpg",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "fantasy"
    ]
  },
  {
    "id": "anilist:6",
    "name": "Rukia Kuchiki",
    "series": "Bleach",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b6-25WoBeWMZXBc.png",
    "tags": [
      "action",
      "adventure",
      "supernatural"
    ]
  },
  {
    "id": "anilist:222594",
    "name": "Momo Ayase",
    "series": "DAN DA DAN",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b222594-24Jn7qlI5spH.png",
    "tags": [
      "action",
      "comedy",
      "drama",
      "romance"
    ]
  },
  {
    "id": "anilist:88889",
    "name": "Raphtalia",
    "series": "The Rising of the Shield Hero",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b88889-CWYytVbCOPsV.png",
    "tags": [
      "action",
      "adventure",
      "fantasy"
    ]
  },
  {
    "id": "anilist:128106",
    "name": "Chizuru Ichinose",
    "series": "Rent-a-Girlfriend",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b128106-zSTsuULvz6PX.png",
    "tags": [
      "comedy",
      "drama",
      "romance"
    ]
  },
  {
    "id": "anilist:7373",
    "name": "Holo",
    "series": "Eromanga Sensei",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b7373-1BH0gELuZmHD.jpg",
    "tags": [
      "comedy",
      "drama",
      "ecchi",
      "romance"
    ]
  },
  {
    "id": "anilist:88349",
    "name": "Eris Boreas Greyrat",
    "series": "Mushoku Tensei: Jobless Reincarnation",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b88349-5dsNUah3oBj8.png",
    "tags": [
      "adventure",
      "drama",
      "ecchi",
      "fantasy"
    ]
  },
  {
    "id": "anilist:908",
    "name": "Yoruichi Shihouin",
    "series": "Bleach",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b908-JSYUkJLCw1f0.png",
    "tags": [
      "action",
      "adventure",
      "supernatural"
    ]
  },
  {
    "id": "anilist:260329",
    "name": "Chisato Nishikigi",
    "series": "Lycoris Recoil",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b260329-1Z5n1QgViEBI.png",
    "tags": [
      "action",
      "slice of life"
    ]
  },
  {
    "id": "anilist:2",
    "name": "Faye Valentine",
    "series": "Cowboy Bebop",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b2-0Iszg6Izgt4p.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "sci-fi"
    ]
  },
  {
    "id": "anilist:65239",
    "name": "Esdeath",
    "series": "Akame ga Kill!",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b65239-2S3t2vSyUew9.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:136072",
    "name": "Mitsuri Kanroji",
    "series": "Demon Slayer: Kimetsu no Yaiba",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b136072-xVwyRUKdpybi.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:168774",
    "name": "Nazuna Nanakusa",
    "series": "Call of the Night",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b168774-zoB9InjmXYq2.png",
    "tags": [
      "comedy",
      "psychological",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:125619",
    "name": "Himiko Toga",
    "series": "My Hero Academia Season 2",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b125619-iQxQoGHJvjRJ.png",
    "tags": [
      "action",
      "adventure",
      "comedy"
    ]
  },
  {
    "id": "anilist:261674",
    "name": "Nijika Ijichi",
    "series": "BOCCHI THE ROCK!",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b261674-a8tJYvtzqWgC.png",
    "tags": [
      "comedy",
      "music",
      "slice of life"
    ]
  },
  {
    "id": "anilist:218648",
    "name": "Hina Chouno",
    "series": "Blue Box",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b218648-kXxXy8lPkeGV.png",
    "tags": [
      "romance",
      "slice of life",
      "sports"
    ]
  },
  {
    "id": "anilist:50389",
    "name": "Rias Gremory",
    "series": "High School DxD",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b50389-gIhJkyk8xj1P.png",
    "tags": [
      "action",
      "comedy",
      "ecchi",
      "fantasy"
    ]
  },
  {
    "id": "anilist:121052",
    "name": "Tanya Degurechaff",
    "series": "Saga of Tanya the Evil",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b121052-bQZT3nIvaryX.png",
    "tags": [
      "action",
      "fantasy"
    ]
  },
  {
    "id": "anilist:67069",
    "name": "Yui Yuigahama",
    "series": "My Teen Romantic Comedy SNAFU",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b67069-6B3xnHfJUO0F.png",
    "tags": [
      "comedy",
      "drama",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:19565",
    "name": "Yui Hirasawa",
    "series": "K-ON!",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b19565-7gMiEAm7NGNK.png",
    "tags": [
      "comedy",
      "music",
      "slice of life"
    ]
  },
  {
    "id": "anilist:121725",
    "name": "Emma",
    "series": "The Promised Neverland",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b121725-LQciVJOjnMVh.png",
    "tags": [
      "drama",
      "fantasy",
      "horror",
      "mystery"
    ]
  },
  {
    "id": "anilist:4963",
    "name": "Yuno Gasai",
    "series": "The Future Diary",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b4963-7ZMcCtXW5hkY.png",
    "tags": [
      "action",
      "horror",
      "mystery",
      "psychological"
    ]
  },
  {
    "id": "anilist:172759",
    "name": "Ai Hoshino",
    "series": "OSHI NO KO",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b172759-cccVhJ2fQA92.png",
    "tags": [
      "drama",
      "mystery",
      "psychological",
      "supernatural"
    ]
  },
  {
    "id": "anilist:674",
    "name": "Kagura",
    "series": "Gintama",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b674-w8wCh0A5Qa8R.png",
    "tags": [
      "action",
      "comedy",
      "drama",
      "sci-fi"
    ]
  },
  {
    "id": "anilist:203384",
    "name": "Akane Kurokawa",
    "series": "OSHI NO KO",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b203384-YuSppFDMw2wn.png",
    "tags": [
      "drama",
      "mystery",
      "psychological",
      "supernatural"
    ]
  },
  {
    "id": "anilist:19566",
    "name": "Mio Akiyama",
    "series": "K-ON!",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b19566-XKsMgf370b4m.png",
    "tags": [
      "comedy",
      "music",
      "slice of life"
    ]
  },
  {
    "id": "anilist:1555",
    "name": "Hinata Hyuuga",
    "series": "Naruto",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b1555-Q41GLTV3FvYF.png",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "drama"
    ]
  },
  {
    "id": "anilist:82525",
    "name": "Shiro",
    "series": "No Game, No Life",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b82525-sKk2FGRKN4aK.png",
    "tags": [
      "adventure",
      "comedy",
      "ecchi",
      "fantasy"
    ]
  },
  {
    "id": "anilist:264529",
    "name": "Ryou Yamada",
    "series": "BOCCHI THE ROCK!",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b264529-BvEusZnJLD2Y.png",
    "tags": [
      "comedy",
      "music",
      "slice of life"
    ]
  },
  {
    "id": "anilist:89363",
    "name": "Darkness",
    "series": "KONOSUBA -God's blessing on this wonderful world!",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b89363-mm21Ll4NegUD.png",
    "tags": [
      "adventure",
      "comedy",
      "ecchi",
      "fantasy"
    ]
  },
  {
    "id": "anilist:120974",
    "name": "Kanna Kamui",
    "series": "Miss Kobayashi's Dragon Maid",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b120974-cZHsjS8DX9WW.png",
    "tags": [
      "comedy",
      "fantasy",
      "slice of life"
    ]
  },
  {
    "id": "anilist:89221",
    "name": "Ochako Uraraka",
    "series": "My Hero Academia",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b89221-gSF2a4gPbG4m.png",
    "tags": [
      "action",
      "adventure",
      "comedy"
    ]
  },
  {
    "id": "anilist:89122",
    "name": "Albedo",
    "series": "Overlord",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b89122-Gj7MBs7F5cMJ.png",
    "tags": [
      "action",
      "adventure",
      "fantasy"
    ]
  },
  {
    "id": "anilist:129330",
    "name": "Echidna",
    "series": "Re:ZERO -Starting Life in Another World- Season 2",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b129330-ZUtYw4n7N0uH.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:245466",
    "name": "Aira Shiratori",
    "series": "DAN DA DAN",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b245466-rd5I5mchZ3bv.png",
    "tags": [
      "action",
      "comedy",
      "drama",
      "romance"
    ]
  },
  {
    "id": "anilist:35253",
    "name": "Mayuri Shiina",
    "series": "Steins;Gate",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b35253-u6QVgLLyHq2W.png",
    "tags": [
      "drama",
      "psychological",
      "sci-fi",
      "thriller"
    ]
  },
  {
    "id": "anilist:130716",
    "name": "Iris",
    "series": "Fire Force",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/n130716-5564jUgQxK9a.png",
    "tags": [
      "action",
      "drama",
      "sci-fi",
      "supernatural"
    ]
  },
  {
    "id": "anilist:88951",
    "name": "Nao Tomori",
    "series": "Charlotte",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/88951-bRm610RrrXp9.jpg",
    "tags": [
      "comedy",
      "drama",
      "romance",
      "sci-fi"
    ]
  },
  {
    "id": "anilist:125736",
    "name": "Elaina",
    "series": "Wandering Witch: The Journey of Elaina",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b125736-LIaof9PjXvH3.png",
    "tags": [
      "adventure",
      "fantasy",
      "slice of life"
    ]
  },
  {
    "id": "anilist:282389",
    "name": "Asa Mitaka",
    "series": "Chainsaw Man",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b282389-Mr4vAa8Du2Jx.jpg",
    "tags": [
      "action",
      "comedy",
      "drama",
      "horror"
    ]
  },
  {
    "id": "anilist:13701",
    "name": "Mikoto Misaka",
    "series": "A Certain Magical Index",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b13701-aFJLRPGAWAae.png",
    "tags": [
      "action",
      "sci-fi",
      "supernatural"
    ]
  },
  {
    "id": "anilist:268676",
    "name": "Kaoruko Waguri",
    "series": "The Fragrant Flower Blooms With Dignity",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b268676-aQmqvqj0DNoJ.png",
    "tags": [
      "comedy",
      "drama",
      "romance"
    ]
  },
  {
    "id": "anilist:127633",
    "name": "Rio Futaba",
    "series": "Rascal Does Not Dream of Bunny Girl Senpai",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b127633-FcCwWK5sQRhK.png",
    "tags": [
      "comedy",
      "drama",
      "mystery",
      "psychological"
    ]
  },
  {
    "id": "anilist:51347",
    "name": "Akeno Himejima",
    "series": "High School DxD",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b51347-YMb9fndAriXd.png",
    "tags": [
      "action",
      "comedy",
      "ecchi",
      "fantasy"
    ]
  },
  {
    "id": "anilist:1120",
    "name": "Shirley Fenette",
    "series": "Code Geass: Lelouch of the Rebellion",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b1120-hjOjinw5j4FE.png",
    "tags": [
      "action",
      "drama",
      "mecha",
      "sci-fi"
    ]
  },
  {
    "id": "anilist:87655",
    "name": "Ais Wallenstein",
    "series": "Is It Wrong to Try to Pick Up Girls in a Dungeon?",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b87655-50i1Y554Vs3z.png",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "fantasy"
    ]
  },
  {
    "id": "anilist:126374",
    "name": "Yotsuba Nakano",
    "series": "The Quintessential Quintuplets",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b126374-Aal36iSQ5nKz.png",
    "tags": [
      "comedy",
      "drama",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:43814",
    "name": "Yona",
    "series": "Yona of the Dawn",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b43814-M0nlr2AP7vY0.png",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "drama"
    ]
  },
  {
    "id": "anilist:83017",
    "name": "Shinoa Hiiragi",
    "series": "Seraph of the End: Vampire Reign",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b83017-XXdnbunnBdTd.png",
    "tags": [
      "action",
      "drama",
      "fantasy",
      "mystery"
    ]
  },
  {
    "id": "anilist:120970",
    "name": "Tohru",
    "series": "Miss Kobayashi's Dragon Maid",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b120970-knjWLdlQIs1y.jpg",
    "tags": [
      "comedy",
      "fantasy",
      "slice of life"
    ]
  },
  {
    "id": "anilist:52723",
    "name": "Kosaki Onodera",
    "series": "Nisekoi",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b52723-YbLFn4JmoAVQ.png",
    "tags": [
      "comedy",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:139038",
    "name": "Kanao Tsuyuri",
    "series": "Demon Slayer: Kimetsu no Yaiba",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b139038-OcOoDUyLEsRn.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:46490",
    "name": "Annie Leonhart",
    "series": "Attack on Titan",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b46490-tan274Ifc1Jf.jpg",
    "tags": [
      "action",
      "drama",
      "fantasy",
      "mystery"
    ]
  },
  {
    "id": "anilist:144594",
    "name": "Kobeni Higashiyama",
    "series": "Chainsaw Man",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b144594-0dbO1NSYeZ12.png",
    "tags": [
      "action",
      "drama",
      "horror",
      "supernatural"
    ]
  },
  {
    "id": "anilist:124696",
    "name": "Hayase Nagatoro",
    "series": "DON'T TOY WITH ME, MISS NAGATORO",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b124696-du2Kszxelh1S.png",
    "tags": [
      "comedy",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:284163",
    "name": "Rebecca",
    "series": "Cyberpunk: Edgerunners",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b284163-tt8smoAXl24x.jpg",
    "tags": [
      "action",
      "drama",
      "psychological",
      "sci-fi"
    ]
  },
  {
    "id": "anilist:37832",
    "name": "Madoka Kaname",
    "series": "Puella Magi Madoka Magica",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b37832-lzVj5IkUciLd.jpg",
    "tags": [
      "action",
      "drama",
      "fantasy",
      "mahou shoujo"
    ]
  },
  {
    "id": "anilist:88708",
    "name": "Kumiko Oumae",
    "series": "Sound! Euphonium",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b88708-ZiVPl8LjIjaK.jpg",
    "tags": [
      "drama",
      "music",
      "slice of life"
    ]
  },
  {
    "id": "anilist:123283",
    "name": "Noelle Silva",
    "series": "Black Clover",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b123283-7nJHtKha0LSm.png",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "fantasy"
    ]
  },
  {
    "id": "anilist:55147",
    "name": "Shino Asada",
    "series": "Sword Art Online II",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b55147-1fCU8lONEuZQ.png",
    "tags": [
      "action",
      "adventure",
      "fantasy",
      "sci-fi"
    ]
  },
  {
    "id": "anilist:8439",
    "name": "Maka Albarn",
    "series": "Soul Eater",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b8439-5TIyWlfClnMs.png",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "fantasy"
    ]
  },
  {
    "id": "anilist:124586",
    "name": "Rin Shima",
    "series": "Laid-Back Camp",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b124586-9lGoHg1zZkFr.png",
    "tags": [
      "comedy",
      "slice of life"
    ]
  },
  {
    "id": "anilist:18",
    "name": "Haruhi Fujioka",
    "series": "Ouran High School Host Club",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b18-SAz5kAo2Fhm1.png",
    "tags": [
      "comedy",
      "drama",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:121514",
    "name": "Mitsuha Miyamizu",
    "series": "Your Name.",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b121514-MGI7JRluscpz.png",
    "tags": [
      "drama",
      "romance",
      "supernatural"
    ]
  },
  {
    "id": "anilist:701",
    "name": "Nana Komatsu",
    "series": "NANA",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b701-gNKbnxT6dbrf.png",
    "tags": [
      "drama",
      "music",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:122687",
    "name": "Mary Saotome",
    "series": "Kakegurui",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b122687-jl1wk9rjO57e.png",
    "tags": [
      "drama",
      "mystery",
      "psychological"
    ]
  },
  {
    "id": "anilist:22050",
    "name": "Nadeko Sengoku",
    "series": "Bakemonogatari",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b22050-RUw3vyGYdr9W.jpg",
    "tags": [
      "comedy",
      "drama",
      "mystery",
      "psychological"
    ]
  },
  {
    "id": "anilist:22052",
    "name": "Mayoi Hachikuji",
    "series": "Bakemonogatari",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b22052-beyfl4AyMGhn.png",
    "tags": [
      "comedy",
      "drama",
      "mystery",
      "psychological"
    ]
  },
  {
    "id": "anilist:75284",
    "name": "Erina Nakiri",
    "series": "Food Wars!",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b75284-4Hiyq7DOwvy7.png",
    "tags": [
      "comedy",
      "ecchi"
    ]
  },
  {
    "id": "anilist:61371",
    "name": "Mashiro Shiina",
    "series": "The Pet Girl of Sakurasou",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b61371-rhWX0wz2DDs3.jpg",
    "tags": [
      "comedy",
      "drama",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:63845",
    "name": "Kyouko Kirigiri",
    "series": "Danganronpa: The Animation",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b63845-43rWjycWhYFF.png",
    "tags": [
      "horror",
      "mystery",
      "psychological",
      "sci-fi"
    ]
  },
  {
    "id": "anilist:16342",
    "name": "Hancock Boa",
    "series": "ONE PIECE",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b16342-kVOF6V5Q94go.png",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "drama"
    ]
  },
  {
    "id": "anilist:55133",
    "name": "Eru Chitanda",
    "series": "Hyouka",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b55133-S7lRrP0gKXpX.png",
    "tags": [
      "mystery",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:131106",
    "name": "Tsukasa Yuzaki",
    "series": "TONIKAWA: Over The Moon For You",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b131106-ZJOpYOpurcYS.png",
    "tags": [
      "comedy",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:6977",
    "name": "Sawako Kuronuma",
    "series": "Kimi ni Todoke: From Me to You",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b6977-rCtlFRoYgE07.png",
    "tags": [
      "comedy",
      "drama",
      "romance",
      "slice of life"
    ]
  },
  {
    "id": "anilist:90181",
    "name": "Beatrice",
    "series": "Re:ZERO -Starting Life in Another World-",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b90181-wRPm0OEaucmw.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:89223",
    "name": "Tsuyu Asui",
    "series": "My Hero Academia",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b89223-5762vburxnlz.png",
    "tags": [
      "action",
      "adventure",
      "comedy"
    ]
  },
  {
    "id": "anilist:138789",
    "name": "Hae-In Cha",
    "series": "Solo Leveling",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b138789-AhE8m0LWjE7E.png",
    "tags": [
      "action",
      "adventure",
      "fantasy"
    ]
  },
  {
    "id": "anilist:5186",
    "name": "Lucy Heartfilia",
    "series": "Fairy Tail",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b5186-izgXf2S86K9u.png",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "fantasy"
    ]
  },
  {
    "id": "anilist:123213",
    "name": "Suzune Horikita",
    "series": "Classroom of the Elite",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b123213-jUfrGBXfW7BL.png",
    "tags": [
      "drama",
      "psychological"
    ]
  },
  {
    "id": "anilist:81931",
    "name": "Fubuki",
    "series": "One-Punch Man",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b81931-fmouMoprPVbV.png",
    "tags": [
      "action",
      "comedy",
      "sci-fi",
      "supernatural"
    ]
  },
  {
    "id": "anilist:423",
    "name": "Casca",
    "series": "Berserk",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b423-AmVFCaJJOBsc.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:3105",
    "name": "Shiki Ryougi",
    "series": "the Garden of sinners Chapter 1: Thanatos. (Overlooking View)",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b3105-lI0m8vJ3JQK1.png",
    "tags": [
      "action",
      "mystery",
      "supernatural",
      "thriller"
    ]
  },
  {
    "id": "anilist:87511",
    "name": "Mako Mankanshoku",
    "series": "Kill la Kill",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b87511-T8lwlQKd6SoK.png",
    "tags": [
      "action",
      "comedy",
      "ecchi"
    ]
  },
  {
    "id": "anilist:89897",
    "name": "Kyouka Jirou",
    "series": "My Hero Academia",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b89897-5vU7N3ayiKRr.png",
    "tags": [
      "action",
      "adventure",
      "comedy"
    ]
  },
  {
    "id": "anilist:144596",
    "name": "Himeno",
    "series": "Chainsaw Man",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b144596-kvL6SD2litJu.png",
    "tags": [
      "action",
      "drama",
      "horror",
      "supernatural"
    ]
  },
  {
    "id": "anilist:88346",
    "name": "Sylphiette",
    "series": "Mushoku Tensei: Jobless Reincarnation",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b88346-h8kCL93AXj4n.png",
    "tags": [
      "adventure",
      "drama",
      "ecchi",
      "fantasy"
    ]
  },
  {
    "id": "anilist:21173",
    "name": "Azusa Nakano",
    "series": "K-ON!",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b21173-0RB5dOJdGt9y.png",
    "tags": [
      "comedy",
      "music",
      "slice of life"
    ]
  },
  {
    "id": "anilist:63",
    "name": "Winry Rockbell",
    "series": "Fullmetal Alchemist: Brotherhood",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/63-xloedtYxiJ2E.jpg",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:62481",
    "name": "Krista Lenz",
    "series": "Attack on Titan",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b62481-ZZDa7vn17lMU.png",
    "tags": [
      "action",
      "drama",
      "fantasy",
      "mystery"
    ]
  },
  {
    "id": "anilist:71479",
    "name": "Ymir",
    "series": "Attack on Titan",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b71479-huCD908XIdqv.png",
    "tags": [
      "action",
      "drama",
      "fantasy",
      "mystery"
    ]
  },
  {
    "id": "anilist:62501",
    "name": "Petra Ral",
    "series": "Attack on Titan",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/n62501-CfTtAAgs64nE.jpg",
    "tags": [
      "action",
      "drama",
      "fantasy",
      "mystery"
    ]
  },
  {
    "id": "anilist:86017",
    "name": "Hitch Dreyse",
    "series": "Attack on Titan",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b86017-m6vXFRKWMwUo.jpg",
    "tags": [
      "action",
      "drama",
      "fantasy",
      "mystery"
    ]
  },
  {
    "id": "anilist:62475",
    "name": "Carla Yeager",
    "series": "Attack on Titan",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/n62475-CExspVnLfweu.png",
    "tags": [
      "action",
      "drama",
      "fantasy",
      "mystery"
    ]
  },
  {
    "id": "anilist:88576",
    "name": "Ram",
    "series": "Re:ZERO -Starting Life in Another World-",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b88576-NWkotUiJ3mK3.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:90185",
    "name": "Crusch Karsten",
    "series": "Re:ZERO -Starting Life in Another World-",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b90185-FR9JHyNe5038.jpg",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:90186",
    "name": "Priscilla Barielle",
    "series": "Re:ZERO -Starting Life in Another World-",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b90186-yr2PT4gI2qa3.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:88574",
    "name": "Felt",
    "series": "Re:ZERO -Starting Life in Another World-",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b88574-Hau8t0GlMvhp.jpg",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:143378",
    "name": "Frederica Baumann",
    "series": "Re:ZERO -Starting Life in Another World-",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b143378-1pXqjZho4dhz.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:90180",
    "name": "Elsa Granhiert",
    "series": "Re:ZERO -Starting Life in Another World-",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b90180-YXbXfcSlalav.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:141858",
    "name": "Petra Leyte",
    "series": "Re:ZERO -Starting Life in Another World-",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b141858-wO0Uj6o4OpUI.jpg",
    "tags": [
      "action",
      "adventure",
      "drama",
      "fantasy"
    ]
  },
  {
    "id": "anilist:21960",
    "name": "Lisa Lisa",
    "series": "JoJo's Bizarre Adventure (TV)",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b21960-3stfLc0uwgoT.png",
    "tags": [
      "action",
      "adventure",
      "supernatural"
    ]
  },
  {
    "id": "anilist:21962",
    "name": "Suzie Q",
    "series": "JoJo's Bizarre Adventure (TV)",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b21962-74U6QodPnwtC.png",
    "tags": [
      "action",
      "adventure",
      "supernatural"
    ]
  },
  {
    "id": "anilist:21937",
    "name": "Erina Pendleton",
    "series": "JoJo's Bizarre Adventure (TV)",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b21937-mwAbJAgxE8yP.jpg",
    "tags": [
      "action",
      "adventure",
      "supernatural"
    ]
  },
  {
    "id": "anilist:129824",
    "name": "Holly Kuujou",
    "series": "JoJo's Bizarre Adventure (TV)",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/n129824-xj6lCSzsoS0M.png",
    "tags": [
      "action",
      "adventure",
      "supernatural"
    ]
  },
  {
    "id": "anilist:232365",
    "name": "Kisha",
    "series": "JoJo's Bizarre Adventure (TV)",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b232365-gPF7YAkx8cY4.png",
    "tags": [
      "action",
      "adventure",
      "supernatural"
    ]
  },
  {
    "id": "anilist:243876",
    "name": "Elizabeth I",
    "series": "JoJo's Bizarre Adventure (TV)",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b243876-AVfx0NlLNGpU.png",
    "tags": [
      "action",
      "adventure",
      "supernatural"
    ]
  },
  {
    "id": "anilist:388258",
    "name": "Imushitsu no Sensei",
    "series": "JoJo's Bizarre Adventure: Stardust Crusaders",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b388258-sSTHsosBXnqo.png",
    "tags": [
      "action",
      "adventure",
      "supernatural"
    ]
  },
  {
    "id": "anilist:389592",
    "name": "Kankoukyaku B",
    "series": "JoJo's Bizarre Adventure: Stardust Crusaders",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/default.jpg",
    "tags": [
      "action",
      "adventure",
      "supernatural"
    ]
  },
  {
    "id": "anilist:27153",
    "name": "Trish Una",
    "series": "JoJo's Bizarre Adventure: Golden Wind",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b27153-D3ru0eppKXRu.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "mystery"
    ]
  },
  {
    "id": "anilist:218918",
    "name": "Anita",
    "series": "JoJo's Bizarre Adventure: Golden Wind",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b218918-sOwPIh3dHcyl.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "mystery"
    ]
  },
  {
    "id": "anilist:250800",
    "name": "Giorno no Hahaoya",
    "series": "JoJo's Bizarre Adventure: Golden Wind",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b250800-d9n7qnCAZcrG.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "mystery"
    ]
  },
  {
    "id": "anilist:242576",
    "name": "Menini",
    "series": "JoJo's Bizarre Adventure: Golden Wind",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b242576-GKPR05BtI34u.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "mystery"
    ]
  },
  {
    "id": "anilist:13369",
    "name": "Hermes Costello",
    "series": "JoJo's Bizarre Adventure: STONE OCEAN",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b13369-7lNj3c1ohOVz.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "supernatural"
    ]
  },
  {
    "id": "anilist:130608",
    "name": "Gwess",
    "series": "JoJo's Bizarre Adventure: STONE OCEAN",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/n130608-zdSdODc414QR.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "supernatural"
    ]
  },
  {
    "id": "anilist:130609",
    "name": "Miuccia Miuller",
    "series": "JoJo's Bizarre Adventure: STONE OCEAN",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/n130609-i14gtS4XDRkX.png",
    "tags": [
      "action",
      "adventure",
      "drama",
      "supernatural"
    ]
  },
  {
    "id": "anilist:82037",
    "name": "Kurokami no Onna",
    "series": "Death Parade",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b82037-xvKHWk4AE4df.png",
    "tags": [
      "drama",
      "mystery",
      "psychological",
      "supernatural"
    ]
  },
  {
    "id": "anilist:88681",
    "name": "Nona",
    "series": "Death Parade",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b88681-tTuJXN5ds3gy.png",
    "tags": [
      "drama",
      "mystery",
      "psychological",
      "supernatural"
    ]
  },
  {
    "id": "anilist:88789",
    "name": "Castra",
    "series": "Death Parade",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b88789-hPssZIZLIk5Z.png",
    "tags": [
      "drama",
      "mystery",
      "psychological",
      "supernatural"
    ]
  },
  {
    "id": "anilist:158572",
    "name": "Mai Takada",
    "series": "Death Parade",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b158572-G4Gw9eWBtyxy.png",
    "tags": [
      "drama",
      "mystery",
      "psychological",
      "supernatural"
    ]
  },
  {
    "id": "anilist:161541",
    "name": "Sachiko Uemura",
    "series": "Death Parade",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b161541-e5f63aRZ8SaN.png",
    "tags": [
      "drama",
      "mystery",
      "psychological",
      "supernatural"
    ]
  },
  {
    "id": "anilist:624",
    "name": "Seras Victoria",
    "series": "Hellsing Ultimate",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b624-qdFGCDB5Zhco.png",
    "tags": [
      "action",
      "horror",
      "supernatural"
    ]
  },
  {
    "id": "anilist:603",
    "name": "Integra Fairbrook Wingates Hellsing",
    "series": "Hellsing Ultimate",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/n603-APJJRPduEnJV.jpg",
    "tags": [
      "action",
      "horror",
      "supernatural"
    ]
  },
  {
    "id": "anilist:678",
    "name": "Bulma",
    "series": "Dragon Ball Z",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b678-2YCe13F0tFos.jpg",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "fantasy"
    ]
  },
  {
    "id": "anilist:2111",
    "name": "Videl",
    "series": "Dragon Ball Z",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b2111-9XqkV0tpjRPB.png",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "fantasy"
    ]
  },
  {
    "id": "anilist:2102",
    "name": "Chi-Chi",
    "series": "Dragon Ball Z",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/2102.jpg",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "fantasy"
    ]
  },
  {
    "id": "anilist:2105",
    "name": "Lunch",
    "series": "Dragon Ball Z",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/2105-u5dq4fBpSho9.png",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "fantasy"
    ]
  },
  {
    "id": "anilist:3168",
    "name": "Pan",
    "series": "Dragon Ball Z",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/3168.jpg",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "fantasy"
    ]
  },
  {
    "id": "anilist:677",
    "name": "Pu'ar",
    "series": "Dragon Ball Z",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b677-PTNZaPeuV1Dx.jpg",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "fantasy"
    ]
  },
  {
    "id": "anilist:2107",
    "name": "Bulma no Mama",
    "series": "Dragon Ball Z",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/2107.jpg",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "fantasy"
    ]
  },
  {
    "id": "anilist:2106",
    "name": "Marron",
    "series": "Dragon Ball Z",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/2106.jpg",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "fantasy"
    ]
  },
  {
    "id": "anilist:3182",
    "name": "Arale Norimaki",
    "series": "Dragon Ball Super",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b3182-x4O8F7qRjlhG.png",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "fantasy"
    ]
  },
  {
    "id": "anilist:2143",
    "name": "Mai",
    "series": "Dragon Ball Super",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/2143.jpg",
    "tags": [
      "action",
      "adventure",
      "comedy",
      "fantasy"
    ]
  },
  {
    "id": "anilist:249154",
    "name": "Kara",
    "series": "Star Wars: Visions",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b249154-aYnA2YYnfe2K.jpg",
    "tags": [
      "action",
      "adventure",
      "sci-fi"
    ]
  },
  {
    "id": "anilist:249146",
    "name": "Am",
    "series": "Star Wars: Visions",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b249146-T4ReTQvzlArn.jpg",
    "tags": [
      "action",
      "adventure",
      "sci-fi"
    ]
  },
  {
    "id": "anilist:249166",
    "name": "Ochou",
    "series": "Star Wars: Visions",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b249166-jeEWKgIc2Dyh.png",
    "tags": [
      "action",
      "adventure",
      "sci-fi"
    ]
  },
  {
    "id": "anilist:249135",
    "name": "Yatou no Boss",
    "series": "Star Wars: Visions",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b249135-TPuHEr4GPPWf.png",
    "tags": [
      "action",
      "adventure",
      "sci-fi"
    ]
  },
  {
    "id": "anilist:249173",
    "name": "Masago",
    "series": "Star Wars: Visions",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b249173-1QdBLpl63sFX.png",
    "tags": [
      "action",
      "adventure",
      "sci-fi"
    ]
  },
  {
    "id": "anilist:15380",
    "name": "Leia Organa",
    "series": "Star Wars: A New Hope",
    "image": "https://s4.anilist.co/file/anilistcdn/character/large/b15380-716gBOHGvwnh.png",
    "tags": [
      "adventure",
      "sci-fi"
    ]
  }
];
