/**
 * Writes `src/shared/wardrobe.ts` from the four art manifests.
 *
 * The whole reason this script exists: **the roll happens on the server and
 * the art does not live there.** `src/client/avatar/` drags six thousand image
 * files behind it (378 Kit PNGs, the Sutemo sheet, 2,355 Snake WebP, 3,808
 * Makowka WebP) and a Durable Object cannot import that. So the pool is split:
 * ids and nothing else go to `shared/`, the pictures stay on the client, and
 * this script is the join. Same bargain as `layers.ts` and both `data.ts`.
 *
 * `wardrobe.test.ts` reads both sides and fails if they disagree, so a set
 * added without rerunning this is caught rather than shipped.
 *
 *   npm run build:wardrobe
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { SETS } from '../src/client/avatar/manifest.js';
import { floorOf, poolOf } from '../src/client/avatar/wardrobeSplit.js';

const ROOT = path.resolve(import.meta.dirname, '..');

const sets = SETS.map((set) => ({
  id: set.id,
  name: set.name,
  floor: floorOf(set),
  pool: poolOf(set),
}));

const body = `// GENERATED by scripts/build-wardrobe.ts. Do not edit: rerun it.
import type { WardrobeSet } from './chest.js';

export const WARDROBE: WardrobeSet[] = ${JSON.stringify(sets, null, 2)};
`;

await writeFile(path.join(ROOT, 'src/shared/wardrobe.ts'), body);

for (const set of sets) {
  console.log(`${set.id.padEnd(9)} floor ${String(set.floor.length).padStart(3)}  pool ${String(set.pool.length).padStart(4)}`);
}
console.log(`total pool ${sets.reduce((n, s) => n + s.pool.length, 0)}`);
