/**
 * The answer bank.
 *
 * Its own file because it is data, not rules: three hundred lines of phrases
 * that the reducer only ever draws from. Everything about *how* a puzzle is
 * drawn, masked and scored stayed in `wheel.ts`.
 *
 * It is also the file this game's secret lives in, and keeping it apart makes
 * that easier to see. `bundle.test.ts` builds the real bundle and fails if any
 * answer here reaches the browser; `wheelDisplay.ts` exists precisely so the
 * board can have the constants without this. Nothing on the client may import
 * either this file or `wheel.ts`.
 *
 * Re-exported from `wheel.ts`, which is what the tests already name.
 */

export interface Puzzle {
  category: string;
  answer: string;
}

/**
 * Everyday phrases, so the game turns on spotting the shape of a sentence
 * rather than on trivia. Uppercase A-Z, spaces and apostrophes only; the tests
 * hold the bank to that, because the mask assumes it.
 *
 * Queer answers live in the ordinary categories: MY TWO MUMS is People, same
 * as MY OLDEST FRIEND. A separate 'Pride' category would announce itself the
 * moment it came up and turn a puzzle into a statement, the opposite of the
 * point.
 *
 * The draw is uniform over this flat list, so a category is exactly as common
 * as its share of the bank. Adding to one thins every other one; there is no
 * per-category weighting to adjust.
 *
 * **No leading THE unless the phrase is an idiom that has one.** This shipped
 * once and turned into the only strategy worth having: a third of the bank
 * contained THE, it was over half of every three-letter word, and a player who
 * saw a three-letter gap called T and then H and got paid twice for reading
 * the bank instead of the puzzle. "THE VILLAGE HALL" is VILLAGE HALL; only
 * BREAK THE ICE and its kind keep the article, because taking it out would
 * make them wrong. The bank test pins the ratio, so adding a batch of
 * THE-something answers fails rather than quietly restoring the meta.
 */
export const PUZZLES: readonly Puzzle[] = [
  { category: "Phrase", answer: "BETTER LATE THAN NEVER" },
  { category: "Phrase", answer: "A PIECE OF CAKE" },
  { category: "Phrase", answer: "BREAK THE ICE" },
  { category: "Phrase", answer: "ONCE IN A BLUE MOON" },
  { category: "Phrase", answer: "THE EARLY BIRD" },
  { category: "Phrase", answer: "BACK TO SQUARE ONE" },
  { category: "Phrase", answer: "SPILL THE BEANS" },
  { category: "Phrase", answer: "UNDER THE WEATHER" },
  { category: "Phrase", answer: "COSTS AN ARM AND A LEG" },
  { category: "Phrase", answer: "HIT THE NAIL ON THE HEAD" },
  { category: "Phrase", answer: "A BLESSING IN DISGUISE" },
  { category: "Phrase", answer: "CROSSING MY FINGERS" },
  { category: "Phrase", answer: "SAVED BY THE BELL" },
  { category: "Phrase", answer: "A BAKER'S DOZEN" },
  { category: "Phrase", answer: "THE LAST WORD" },
  { category: "Phrase", answer: "BOB IS YOUR UNCLE" },
  { category: "Phrase", answer: "CHALK AND CHEESE" },
  { category: "Phrase", answer: "SWINGS AND ROUNDABOUTS" },
  { category: "Phrase", answer: "RAINING CATS AND DOGS" },
  { category: "Phrase", answer: "OVER THE MOON" },
  { category: "Phrase", answer: "A DAMP SQUIB" },
  { category: "Phrase", answer: "PULL YOUR SOCKS UP" },
  { category: "Phrase", answer: "MIND THE GAP" },
  { category: "Phrase", answer: "FULL OF BEANS" },
  { category: "Phrase", answer: "A STORM IN A TEACUP" },
  { category: "Phrase", answer: "GOING FOR A SONG" },
  { category: "Phrase", answer: "PLENTY MORE FISH" },
  { category: "Phrase", answer: "NONE THE WISER" },
  { category: "Phrase", answer: "SIXES AND SEVENS" },
  { category: "Phrase", answer: "ROUND THE HOUSES" },
  { category: "Phrase", answer: "ON YOUR BIKE" },
  { category: "Phrase", answer: "A BIT OF A FAFF" },
  { category: "Phrase", answer: "EASY DOES IT" },
  { category: "Phrase", answer: "CHEAP AND CHEERFUL" },
  { category: "Phrase", answer: "HORSES FOR COURSES" },
  { category: "Phrase", answer: "THE PENNY DROPPED" },
  { category: "Phrase", answer: "PUT THE KETTLE ON" },
  { category: "Phrase", answer: "FIRST THINGS FIRST" },
  { category: "Phrase", answer: "THE LONG GAME" },
  { category: "Phrase", answer: "A CLEAN SLATE" },
  { category: "Phrase", answer: "SLEEP ON IT" },
  { category: "Phrase", answer: "WORTH A PUNT" },
  { category: "Phrase", answer: "BITS AND BOBS" },
  { category: "Phrase", answer: "ODDS AND ENDS" },
  { category: "Phrase", answer: "FAIR AND SQUARE" },
  { category: "Phrase", answer: "ALL IN GOOD TIME" },
  { category: "Phrase", answer: "THE DONE THING" },
  { category: "Phrase", answer: "A FLASH IN THE PAN" },
  { category: "Phrase", answer: "MAKING A MEAL OF IT" },
  { category: "Phrase", answer: "A SIGHT FOR SORE EYES" },
  { category: "Phrase", answer: "LOVE IS LOVE" },
  { category: "Phrase", answer: "OUT AND PROUD" },
  { category: "Phrase", answer: "FOUND MY PEOPLE" },
  { category: "Phrase", answer: "FRIEND OF DOROTHY" },
  { category: "Phrase", answer: "WE ARE EVERYWHERE" },
  { category: "Phrase", answer: "HAPPY PRIDE" },

  { category: "Thing", answer: "A CUP OF TEA" },
  { category: "Thing", answer: "MORNING PAPER" },
  { category: "Thing", answer: "A ROLLING SUITCASE" },
  { category: "Thing", answer: "GARDEN SHED" },
  { category: "Thing", answer: "KITCHEN TABLE" },
  { category: "Thing", answer: "A BOX OF CHOCOLATES" },
  { category: "Thing", answer: "WINDOW SEAT" },
  { category: "Thing", answer: "OLD PHOTOGRAPHS" },
  { category: "Thing", answer: "A TATTY UMBRELLA" },
  { category: "Thing", answer: "WELLINGTON BOOTS" },
  { category: "Thing", answer: "A HOT WATER BOTTLE" },
  { category: "Thing", answer: "TELLY REMOTE" },
  { category: "Thing", answer: "A BUS TIMETABLE" },
  { category: "Thing", answer: "TARTAN BLANKET" },
  { category: "Thing", answer: "A LOYALTY CARD" },
  { category: "Thing", answer: "JIGSAW PUZZLE" },
  { category: "Thing", answer: "A PACK OF CARDS" },
  { category: "Thing", answer: "RUSTY BICYCLE" },
  { category: "Thing", answer: "SPARE KEY" },
  { category: "Thing", answer: "A WOOLLY JUMPER" },
  { category: "Thing", answer: "BIRTHDAY CANDLES" },
  { category: "Thing", answer: "A TIN OF BISCUITS" },
  { category: "Thing", answer: "THE GOOD SCISSORS" },
  { category: "Thing", answer: "A PAPER ROUND" },
  { category: "Thing", answer: "A CRACKLING FIRE" },
  { category: "Thing", answer: "A RAINBOW FLAG" },
  { category: "Thing", answer: "A TRANS FLAG" },
  { category: "Thing", answer: "MATCHING WEDDING RINGS" },
  { category: "Thing", answer: "A CARABINER OF KEYS" },
  { category: "Thing", answer: "A FOLDED KEFFIYEH" },
  { category: "Thing", answer: "KEY TO THE OLD HOUSE" },
  { category: "Thing", answer: "A BOWL OF OLIVES" },

  { category: "Place", answer: "BOTTOM OF THE GARDEN" },
  { category: "Place", answer: "A QUIET LIBRARY" },
  { category: "Place", answer: "SOUTH COAST" },
  { category: "Place", answer: "MOUNTAIN VILLAGE" },
  { category: "Place", answer: "CORNER SHOP" },
  { category: "Place", answer: "LOCAL PUB" },
  { category: "Place", answer: "A SEASIDE PIER" },
  { category: "Place", answer: "VILLAGE GREEN" },
  { category: "Place", answer: "A COUNTRY LANE" },
  { category: "Place", answer: "LAKE DISTRICT" },
  { category: "Place", answer: "A CROWDED PLATFORM" },
  { category: "Place", answer: "HIGH STREET" },
  { category: "Place", answer: "A CASTLE ON A HILL" },
  { category: "Place", answer: "ALLOTMENTS" },
  { category: "Place", answer: "SCOTTISH BORDERS" },
  { category: "Place", answer: "A MARKET TOWN" },
  { category: "Place", answer: "BACK GARDEN" },
  { category: "Place", answer: "A WINDSWEPT MOOR" },
  { category: "Place", answer: "GARDEN CENTRE" },
  { category: "Place", answer: "A CANAL TOWPATH" },
  { category: "Place", answer: "A BUSY BUS STATION" },
  { category: "Place", answer: "CHURCH HALL" },
  { category: "Place", answer: "A DISUSED RAILWAY" },
  { category: "Place", answer: "END OF THE PIER" },
  { category: "Place", answer: "A CLIFFTOP PATH" },
  { category: "Place", answer: "VILLAGE HALL" },
  { category: "Place", answer: "A HARBOUR WALL" },
  { category: "Place", answer: "PARK BANDSTAND" },
  { category: "Place", answer: "A NARROW BRIDGE" },
  { category: "Place", answer: "OLD BOOKSHOP" },
  { category: "Place", answer: "A WALLED GARDEN" },
  { category: "Place", answer: "FERRY TERMINAL" },
  { category: "Place", answer: "A FARMERS MARKET" },
  { category: "Place", answer: "TOP OF THE HILL" },
  { category: "Place", answer: "A COBBLED SQUARE" },
  { category: "Place", answer: "LOCAL GAY BAR" },
  { category: "Place", answer: "A RAINBOW CROSSING" },
  { category: "Place", answer: "SOHO ON A SATURDAY" },
  { category: "Place", answer: "QUEER BOOKSHOP" },
  { category: "Place", answer: "A VILLAGE IN GALILEE" },
  { category: "Place", answer: "OLD STONE TERRACES" },
  { category: "Place", answer: "BETHLEHEM AT CHRISTMAS" },
  { category: "Place", answer: "DEAD SEA" },
  { category: "Place", answer: "RIVER JORDAN" },
  { category: "Place", answer: "OLD CITY WALLS" },

  { category: "People", answer: "MY OLDEST FRIEND" },
  { category: "People", answer: "NEW NEIGHBOURS" },
  { category: "People", answer: "A FAMILY OF FIVE" },
  { category: "People", answer: "SUNDAY CROWD" },
  { category: "People", answer: "A GOOD LISTENER" },
  { category: "People", answer: "QUIZ TEAM" },
  { category: "People", answer: "MY LITTLE BROTHER" },
  { category: "People", answer: "EARLY RISERS" },
  { category: "People", answer: "A HOUSE FULL OF COUSINS" },
  { category: "People", answer: "VILLAGE CHOIR" },
  { category: "People", answer: "A GOOD NEIGHBOUR" },
  { category: "People", answer: "WHOLE STREET" },
  { category: "People", answer: "MY GREAT AUNT" },
  { category: "People", answer: "ALLOTMENT LOT" },
  { category: "People", answer: "A CROWD OF STRANGERS" },
  { category: "People", answer: "BOOK GROUP" },
  { category: "People", answer: "MY BEST MAN" },
  { category: "People", answer: "MORNING REGULARS" },
  { category: "People", answer: "A PAIR OF TWINS" },
  { category: "People", answer: "PARISH COUNCIL" },
  { category: "People", answer: "MY GODMOTHER" },
  { category: "People", answer: "FRONT ROW" },
  { category: "People", answer: "A FRIEND OF A FRIEND" },
  { category: "People", answer: "NIGHT SHIFT" },
  { category: "People", answer: "MY OLD SCHOOL FRIENDS" },
  { category: "People", answer: "MY TWO MUMS" },
  { category: "People", answer: "MY CHOSEN FAMILY" },
  { category: "People", answer: "QUEER BOOK CLUB" },
  { category: "People", answer: "A PAIR OF GROOMS" },
  { category: "People", answer: "TWO BRIDES" },
  { category: "People", answer: "MY GAY UNCLE" },
  { category: "People", answer: "A NONBINARY FRIEND" },
  { category: "People", answer: "MY GIRLFRIEND'S MUM" },
  { category: "People", answer: "A FAMILY OF OLIVE FARMERS" },
  { category: "People", answer: "SHEPHERDS ON THE HILLSIDE" },

  { category: "Occupation", answer: "LIGHTHOUSE KEEPER" },
  { category: "Occupation", answer: "FLYING INSTRUCTOR" },
  { category: "Occupation", answer: "BOOKBINDER" },
  { category: "Occupation", answer: "PASTRY CHEF" },
  { category: "Occupation", answer: "DRY STONE WALLER" },
  { category: "Occupation", answer: "PIANO TUNER" },
  { category: "Occupation", answer: "FISHMONGER" },
  { category: "Occupation", answer: "BLACKSMITH" },
  { category: "Occupation", answer: "PARK RANGER" },
  { category: "Occupation", answer: "TRAIN DRIVER" },
  { category: "Occupation", answer: "CLOCKMAKER" },
  { category: "Occupation", answer: "BEEKEEPER" },
  { category: "Occupation", answer: "SIGN WRITER" },
  { category: "Occupation", answer: "MARKET TRADER" },
  { category: "Occupation", answer: "RIVER PILOT" },
  { category: "Occupation", answer: "WINDOW CLEANER" },
  { category: "Occupation", answer: "POSTAL WORKER" },
  { category: "Occupation", answer: "MIDWIFE" },
  { category: "Occupation", answer: "STONEMASON" },
  { category: "Occupation", answer: "THATCHER" },
  { category: "Occupation", answer: "FARRIER" },
  { category: "Occupation", answer: "LOLLIPOP LADY" },
  { category: "Occupation", answer: "LIBRARIAN" },
  { category: "Occupation", answer: "BOAT BUILDER" },
  { category: "Occupation", answer: "TREE SURGEON" },
  { category: "Occupation", answer: "CHIMNEY SWEEP" },
  { category: "Occupation", answer: "SHEEP FARMER" },
  { category: "Occupation", answer: "GLASSBLOWER" },
  { category: "Occupation", answer: "COBBLER" },
  { category: "Occupation", answer: "LOCK KEEPER" },
  { category: "Occupation", answer: "DRAG PERFORMER" },
  { category: "Occupation", answer: "PRIDE ORGANISER" },

  { category: "Food & Drink", answer: "STRAWBERRIES AND CREAM" },
  { category: "Food & Drink", answer: "HOT BUTTERED TOAST" },
  { category: "Food & Drink", answer: "A POT OF COFFEE" },
  { category: "Food & Drink", answer: "SUNDAY ROAST" },
  { category: "Food & Drink", answer: "LEMON MERINGUE PIE" },
  { category: "Food & Drink", answer: "FISH AND CHIPS" },
  { category: "Food & Drink", answer: "BEANS ON TOAST" },
  { category: "Food & Drink", answer: "A BACON SANDWICH" },
  { category: "Food & Drink", answer: "STICKY TOFFEE PUDDING" },
  { category: "Food & Drink", answer: "SHEPHERD'S PIE" },
  { category: "Food & Drink", answer: "A CREAM TEA" },
  { category: "Food & Drink", answer: "TOAD IN THE HOLE" },
  { category: "Food & Drink", answer: "BANGERS AND MASH" },
  { category: "Food & Drink", answer: "A PLOUGHMAN'S LUNCH" },
  { category: "Food & Drink", answer: "CRUMPETS AND JAM" },
  { category: "Food & Drink", answer: "RHUBARB CRUMBLE" },
  { category: "Food & Drink", answer: "A PINT OF BITTER" },
  { category: "Food & Drink", answer: "ELDERFLOWER CORDIAL" },
  { category: "Food & Drink", answer: "CHEESE AND PICKLE" },
  { category: "Food & Drink", answer: "A CHIP BUTTY" },
  { category: "Food & Drink", answer: "CUSTARD AND JELLY" },
  { category: "Food & Drink", answer: "A SAUSAGE ROLL" },
  { category: "Food & Drink", answer: "JAM ROLY POLY" },
  { category: "Food & Drink", answer: "ZA'ATAR ON WARM BREAD" },
  { category: "Food & Drink", answer: "ORANGES FROM JAFFA" },

  { category: "Around the House", answer: "KITCHEN SINK" },
  { category: "Around the House", answer: "A CREAKING FLOORBOARD" },
  { category: "Around the House", answer: "SPARE ROOM" },
  { category: "Around the House", answer: "LINEN CUPBOARD" },
  { category: "Around the House", answer: "AIRING CUPBOARD" },
  { category: "Around the House", answer: "A DRAUGHTY HALLWAY" },
  { category: "Around the House", answer: "WASHING LINE" },
  { category: "Around the House", answer: "UNDER THE STAIRS" },
  { category: "Around the House", answer: "FRONT DOORSTEP" },
  { category: "Around the House", answer: "A CLUTTERED LOFT" },
  { category: "Around the House", answer: "BATHROOM MIRROR" },
  { category: "Around the House", answer: "A LEAKY RADIATOR" },
  { category: "Around the House", answer: "JUNK DRAWER" },
  { category: "Around the House", answer: "NET CURTAINS" },
  { category: "Around the House", answer: "A PRIDE FLAG IN MY WINDOW" },

  { category: "What Are You Doing?", answer: "READING BY THE WINDOW" },
  { category: "What Are You Doing?", answer: "WALKING THE LONG WAY HOME" },
  { category: "What Are You Doing?", answer: "LEARNING TO SAIL" },
  { category: "What Are You Doing?", answer: "WATCHING RAIN FALL" },
  { category: "What Are You Doing?", answer: "QUEUEING PATIENTLY" },
  { category: "What Are You Doing?", answer: "MOWING THE LAWN" },
  { category: "What Are You Doing?", answer: "MAKING A ROUND OF TEA" },
  { category: "What Are You Doing?", answer: "HAVING A LIE IN" },
  { category: "What Are You Doing?", answer: "FINISHING A CROSSWORD" },
  { category: "What Are You Doing?", answer: "FEEDING NEXT DOOR'S CAT" },
  { category: "What Are You Doing?", answer: "PAINTING A GARDEN FENCE" },
  { category: "What Are You Doing?", answer: "CATCHING THE LAST TRAIN" },
  { category: "What Are You Doing?", answer: "PACKING A PICNIC" },
  { category: "What Are You Doing?", answer: "PUTTING BINS OUT" },
  { category: "What Are You Doing?", answer: "WAITING FOR A BUS" },

  { category: "Nature", answer: "A FIELD OF BLUEBELLS" },
  { category: "Nature", answer: "FROST ON MORNING GRASS" },
  { category: "Nature", answer: "AN ANCIENT OAK TREE" },
  { category: "Nature", answer: "DAWN CHORUS" },
  { category: "Nature", answer: "A HEDGEROW IN SPRING" },
  { category: "Nature", answer: "CONKERS ON THE PATH" },
  { category: "Nature", answer: "A ROBIN IN WINTER" },
  { category: "Nature", answer: "MIST OVER OPEN FIELDS" },
  { category: "Nature", answer: "FALLING LEAVES" },
  { category: "Nature", answer: "A ROCK POOL" },
  { category: "Nature", answer: "HEATHER IN AUGUST" },
  { category: "Nature", answer: "A MURMURATION" },
  { category: "Nature", answer: "SNOWDROPS IN JANUARY" },
  { category: "Nature", answer: "RISING TIDE" },
  { category: "Nature", answer: "A FOX IN THE GARDEN" },
  { category: "Nature", answer: "BRAMBLES AND NETTLES" },
  { category: "Nature", answer: "FIRST SWALLOWS" },
  { category: "Nature", answer: "A CARPET OF MOSS" },
  { category: "Nature", answer: "WIND IN THE REEDS" },
  { category: "Nature", answer: "DEER AT FIRST LIGHT" },
  { category: "Nature", answer: "A CLEAR NIGHT SKY" },
  { category: "Nature", answer: "TOADSTOOLS IN A WOOD" },
  { category: "Nature", answer: "ICICLES ON THE EAVES" },
  { category: "Nature", answer: "A NEST OF SPARROWS" },
  { category: "Nature", answer: "APPLE BLOSSOM" },
  { category: "Nature", answer: "SMELL OF RAIN" },
  { category: "Nature", answer: "SEALS ON A SANDBANK" },
  { category: "Nature", answer: "OLIVE HARVEST" },
  { category: "Nature", answer: "OLIVE GROVES ON A HILL" },
  { category: "Nature", answer: "PRICKLY PEAR CACTUS" },
  { category: "Nature", answer: "ALMOND TREES IN BLOSSOM" },
  { category: "Nature", answer: "FIGS AND POMEGRANATES" },
  { category: "Nature", answer: "A LEMON TREE IN THE YARD" },

  { category: "Weather", answer: "A BRIGHT SPELL" },
  { category: "Weather", answer: "SCATTERED SHOWERS" },
  { category: "Weather", answer: "A HARD FROST" },
  { category: "Weather", answer: "GALES ON THE COAST" },
  { category: "Weather", answer: "MUGGY AND CLOSE" },
  { category: "Weather", answer: "DRIZZLE ALL DAY" },
  { category: "Weather", answer: "A BLUSTERY MORNING" },
  { category: "Weather", answer: "SUNNY INTERVALS" },

  { category: "Pastime", answer: "PUB QUIZ NIGHT" },
  { category: "Pastime", answer: "A LONG COUNTRY WALK" },
  { category: "Pastime", answer: "BIRD WATCHING" },
  { category: "Pastime", answer: "SUNDAY LEAGUE FOOTBALL" },
  { category: "Pastime", answer: "BAKING A SPONGE CAKE" },
  { category: "Pastime", answer: "A CAR BOOT SALE" },
  { category: "Pastime", answer: "A GAME OF DARTS" },
  { category: "Pastime", answer: "KNITTING BY THE FIRE" },
  { category: "Pastime", answer: "SEA SWIMMING" },
  { category: "Pastime", answer: "A BRASS BAND CONCERT" },
  { category: "Pastime", answer: "MARCHING AT PRIDE" },
  { category: "Pastime", answer: "A DRAG BRUNCH" },
  { category: "Pastime", answer: "QUEER FILM NIGHT" },
  { category: "Pastime", answer: "ROLLER DERBY" },
  { category: "Pastime", answer: "A GAME OF BACKGAMMON" },
];

// Small pure helpers
